### PR TITLE
replace projectRoot with watchFolders

### LINKED ISSUE #44: cannot find ./index
enviroment:
Windows 10
latest yarn, ts

git clone repo..
cd yarn && yarn workspace mobile start

bundling failed: Error: Unable to resolve module `./app.json` from `C:\workspace\react-native-web-monorepo\index.js`: The module `./app.json` could not be found from `C:\workspace\react-native-web-monorepo\index.js`. Indeed, none of these files exist:
  * `app.json`

### PR DESCRIPTION
**Pull request by gko**
No need to make a `root: ../../../../`, we can just add a `watchFolders`
field instead.

fixes #44

### CODE REVIEW

**Comment by hosseinmd** [comment]
what is different between watchFolders and projectRoot?

**Comment by gko** [comment]
The `projectRoot` flag tells metro where it can find the entry point (`index.js`).

The problem, as you stated in the issue is that we redefined the entry point in the metro but then pointed the `android` and `ios` app to look into /packages/mobile folder.

It would work perfectly here. But once you copy some other build to this repo you'll have to not only modify a path to `node_modules` folder, but also redefine an entry in `android` and `ios` project (as by default it's set to just `index.js`.

So the issue #44 is pretty common. And as you said the proper fix is to not redefine the `root`/`projectRoot` folders.

**Comment by brunolemos** [comment]
hi, could you cleanup your pr please? rebase with master, only 1 commit in total and only the changes directly related to the issue (without doing other changes like upgrading dependencies, etc)

**Comment by brunolemos** [comment]
Have you tested if release builds continue to work as expected after these changes?
And shouldn't we update the path on `applyNativeModulesSettingsGradle` as well?

**Pull request merged**
